pipeline {
    agent {
        docker { image 'dtzar/helm-kubectl:3' }
    }
    stages {
        stage('Deploy') {
        withKubeConfig([credentialsId: 'aks-kubeconfig'])
            steps {
                sh 'helm list'
            }
        }
    }
}
