pipeline {
    agent {
        docker { image 'dtzar/helm-kubectl:3' }
    }
    stages {
        stage('Deploy') {
        withKubeConfig([credentialsId: 'aks-kubeconfig', serverUrl: 'https://api.k8s.my-company.com'])
            steps {
                sh 'helm list'
            }
        }
    }
}
